create table products
(
    id    int4 generated by default as identity,
    name varchar(255),
    price int4,
    primary key (id)
);
create table purchases
(
    id           int4 generated by default as identity,
    product_name varchar(255),
    quantity     int4,
    primary key (id)
);
INSERT INTO products (name, price)
VALUES ('Apples', 80),
       ('Bananas', 100),
       ('Oranges', 130),
       ('Pears', 150),
       ('Pineapples', 200);
